apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: simplex
  namespace: '937651835502'
  selfLink: /apis/serving.knative.dev/v1/namespaces/937651835502/services/simplex
  uid: 835568dc-48d6-4378-99d0-d3354247c70a
  resourceVersion: AAXuyazibFE
  generation: 4
  creationTimestamp: '2022-12-01T19:37:36.964825Z'
  labels:
    managed-by: gcp-cloud-build-deploy-cloud-run
    gcb-trigger-id: 08900a0c-f81d-4eb5-b5b0-d8afa92eb797
    cloud.googleapis.com/location: europe-west1
  annotations:
    run.googleapis.com/client-name: cloud-console
    serving.knative.dev/creator: machkouroke@gmail.com
    serving.knative.dev/lastModifier: machkouroke@gmail.com
    client.knative.dev/user-image: >-
      gcr.io/lopsimplex/simplex@sha256:28ee45dd24d38b1da55a2755405aa78c07cd2cd21cbb3531328fa3eaaf48c4f4
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      name: simplex-00004-qur
      annotations:
        run.googleapis.com/client-name: cloud-console
        autoscaling.knative.dev/maxScale: '14'
        run.googleapis.com/cpu-throttling: 'false'
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: 937651835502-compute@developer.gserviceaccount.com
      containers:
      - image: >-
          gcr.io/lopsimplex/simplex@sha256:28ee45dd24d38b1da55a2755405aa78c07cd2cd21cbb3531328fa3eaaf48c4f4
        ports:
        - name: http1
          containerPort: 8888
        resources:
          limits:
            cpu: 2000m
            memory: 4Gi
  traffic:
  - percent: 100
    latestRevision: true
