name = "LOPSimplex"
uuid = "c8c3e34f-4835-45dd-878b-201efac5a6be"
authors = ["machkouroke"]
version = "0.1.0"

[deps]
Match = "7eb4fadd-790c-5f42-8a69-bfa0b872bfbf"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
