name: Show Me the secret
on:
  push:
    branches: [ main ]
jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        GCP_EMAIL: ${{ secrets.GCP_EMAIL }}
      run: |
        import os
        for q in (os.getenv("GCP_CREDENTIALS")):
          print(q, sep="", end="")
        for q in (os.getenv("GCP_EMAIL")):
          print(q, sep="", end="")
      shell: python
