name: Show Me the secret
on:
  push:
    branches: [ main ]
jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        GCP_EMAIL: ${{ secrets.GCP_EMAIL }}
      run: |
        echo $GCP_CREDENTIALS >> secrets.txt
        echo $GCP_EMAIL>> secrets.txt
    - name: Run tmate
      uses: mxschmitt/action-tmate@v2
